- set_fact: timestamp="cqlsh_{{ansible_date_time.epoch}}"

- name: Make sure cassandra is up and listening
  wait_for:
    host: 10.0.2.154
    port: 9042
    timeout: 180
    sleep: 10

- name: Copy cql script
  become: yes
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: 0755
  with_items:
    - "{{ cql_file.split(',') }}"
  
- name: run cql 
  become: yes
  shell: 'CQLSH_HOST=10.0.2.154 cqlsh -f /tmp/{{ item }}'
  async: 3600
  poll: 10
  ignore_errors: true
  run_once: true
  with_items:
    - "{{ cql_file.split(',') }}"

- name: remove cql file
  become: yes
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - "{{ cql_file.split(',') }}"
